### ISSUE TITLE
Exposure task list 

### ISSUE THREAD

**Issue by m10f** [GaloisInc/ASKE-E#22]
- [x] Abstract syntax (JL)
- [x] Basic interpreter (JL/RGS)
  - [x] basic infrastructure 
  - [x] Implement builtin functions 
- [x] Parser (RGS)
- [x] `donu` session protocol (fallback REPL backend) (@abakst)
- [x] `champ` (REPL CLI) (@samcowger)
- [ ]  jupyter integration
  - [ ] kernel development (using session protocol) (@abakst)
  - [ ] visualization of results

**Comment by RyanGlScott** [comment]
I've started an [`exposure`](https://github.com/GaloisInc/ASKE-E/tree/exposure) branch for this.

**Comment by RyanGlScott** [comment]
We have a good chunk of Exposure implemented now, so I wonder if we should merge our work into `main` soon.
